-- Create business_activities table in Supabase
-- Based on IFZA Business Activities CSV structure

-- Drop table if exists (for clean recreation)
DROP TABLE IF EXISTS business_activities;

-- Create the business_activities table
CREATE TABLE business_activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    freezone VARCHAR(50) NOT NULL,
    activity_code VARCHAR(50) NOT NULL UNIQUE,
    activity_name TEXT NOT NULL,
    activity_description TEXT,
    activity_type VARCHAR(20) NOT NULL CHECK (activity_type IN ('Professional', 'Commercial')),
    property_requirements TEXT,
    notes TEXT,
    classification TEXT,
    regulation_type VARCHAR(20) NOT NULL DEFAULT 'Non-Regulated' CHECK (regulation_type IN ('Regulated', 'Non-Regulated')),
    approving_entity_1 TEXT,
    approving_entity_2 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_business_activities_freezone ON business_activities(freezone);
CREATE INDEX idx_business_activities_activity_type ON business_activities(activity_type);
CREATE INDEX idx_business_activities_regulation_type ON business_activities(regulation_type);
CREATE INDEX idx_business_activities_activity_name ON business_activities USING gin(to_tsvector('english', activity_name));
CREATE INDEX idx_business_activities_activity_description ON business_activities USING gin(to_tsvector('english', activity_description));
CREATE INDEX idx_business_activities_freezone_type ON business_activities(freezone, activity_type);

-- Enable Row Level Security
ALTER TABLE business_activities ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access to all users (public data)
CREATE POLICY "Allow public read access to business activities" 
ON business_activities FOR SELECT 
TO PUBLIC 
USING (true);

-- Insert all business activities from the CSV
INSERT INTO business_activities (
    freezone, activity_code, activity_name, activity_description, activity_type,
    property_requirements, notes, classification, regulation_type, 
    approving_entity_1, approving_entity_2
) VALUES 
('IFZA', '112005', 'Onshore & Offshore Oil & Gas Fields Services Abroad', 'Includes providing technical and engineering services to enhance and develop production in the fields, it covers well drilling, testing and maintenance, drilling fluids engineering, diving for underwater pipes repair, pipe corrosion control, equipment repair and maintenance.', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '112231504', 'IT Support Services', 'IT solutions & support for established businesses', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122352', 'Ecommerce', 'the activity of electronically buying or selling of products on online services or over the Internet', 'Commercial', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122353', 'Real Estate consultancy (outside of UAE)', 'Includes providing sound advice to potential buyers as well as developing strategies to achieve their goals and objectives out of UAE, it involves showing properties, analyzing sales statistics, sourcing appraisers, referring mortgage service providers, contractors and renovation providers, examining contracts before making offers, closing and escrow expertise.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122356', 'Oil & Natural Gas Well Drilling Abroad', 'Includes the process of drilling in the on and off shore oilfields for the extraction of petroleum after conducting the geological surveys to locate the petroleum reservoirs, the process involves the experimental and developmental drilling as well as constructing the derricks and fixing the casing pipes', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122357', 'Oil & Natural Gas Well Reinforcement Services Abroad', 'Includes firms specialized in reinforcing oil and natural gas wells using various techniques , including activated or processed cement pumping or other materials used to reinforce and coat wells for protection against erosion or interaction with the surrounding natural materials , raise the duration of possible utilization, or to maintain and redrill.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122360', 'Well Drilling & Oil & Natural Gas Development Abroad', 'Includes the process carried outside the UAE for the drilling in the onshore and offshore oilfields for the extraction of petroleum and natural gas.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122361', 'New Motor Vehicles Trading Abroad', 'Includes reselling of new motor vehicle for personal passenger use, or for commercial use.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122362', 'Buses & Trucks Trading (Outside UAE)', 'Includes reselling different passenger buses, as well as trucks and trailers for transporting goods, liquid substances, building materials…etc.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122363', 'Specialized Vehicles Trading Abroad', 'Includes reselling specialized motor vehicles including ambulances, fire engines, garbage collectors , street sweepers, truck- mounted cranes for loading and discharging and truck mixers.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122365', 'Used Vehicles Trading (Outside UAE)', 'Includes reselling used vehicles and trucks for transporting goods, building materials and liquid tankers…etc', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122366', 'Racing Cars Trading Abroad', 'Includes reselling different racing cars, which are exclusively restricted to racing tracks.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122367', 'Trading in Medicines (Outside UAE)', 'Includes reselling of pharmaceuticals, medical supplies, herbal medicines, and alternative medicine drugs.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122368', 'Trading in Pharmaceutical Products (Outside UAE)', 'Includes reselling pharmaceutical products directly used for medication or treatment outside UAE only.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122371', 'Scrap & Metal Waste Trading Abroad', 'Includes reselling metal waste and scrap for recycling, including collecting from different sources, sorting and stripping reusable goods such as parts from car wrecks, no real transformation process should be involved, firms practicing this activity are not allowed to deal in military waste and scrap such as weapons and explosives.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122372', 'Fuel Supply Services (Outside UAE)', 'Includes firms engaged in supplying sea and air transport companies, industrial firms, power generating plants with fuel and lubricants and other similar materials to operate machinery and equipment.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122373', 'Petroleum Transport (Outside UAE)', 'Includes firms transporting petroleum products and derivatives on tanks and as per order', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122374', 'Sea Transport of Oil & Petroleum Products (Outside UAE)', 'Includes the bulk transport of unrefined crude from its point of oil extraction to refineries by crude tankers, and also moving refined products and petrochemicals refineries to consuming markets.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122375', 'Professional & Management Development Training Abroad', 'Includes institutions primarily engaged in offering an array of short duration courses for management, professional and personal development, including providing training in areas such as education, social and behavioral development, management, secretarial, legal, HR, insurance, accounting, sales, banking and finance, advertising and market…etc.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122376', 'Diesel Fuel Trading (Outside UAE)', 'Includes reselling diesel fuel, not directly to customers, but to industrial and commercial corporations for fuelling vehicles, ships, planes or in industrial or marine equipment, this activity neither involves petrol station which is classified under activity No. 505001, nor the firms that practice the activity no. 505002.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122377', 'Aircraft Spare Parts & Components Trading Abroad', 'Includes reselling of spare parts and other components for aircraft reparation, maintenance, renovation and efficiency upgrading, as well as provision of safety and security systems or others. outside of UAE.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122378', 'Real Estate Buying & Selling Brokerage Abroad', 'Includes firms engaged in real estate brokerage or be agents, they mainly involve in buying, selling or appraisal activities.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122379', 'Renewable Energy Engineering Consultancy Abroad', 'Includes conducting engineering consultancy and services regarding utilizing renewable energy specially winds, tidal waves, solar energy, hydrogen, as a clean alternative to traditional energy, it involves technical and economic feasibility studies, identify alternatives as well as preparing architectural designs and supervise execution, the minimal qualifications required is bachelor degree in renewable energy, electrical or mechanical engineering, along with three years hands-on experience.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122380', 'Architectural Design Consultancy Abroad', 'Includes firms engaged in providing consultancies and services related to architectural engineering, including preparing preliminary and final engineering and technical studies for construction projects as well as interior design and landscaping, the minimal qualifications required is bachelor degree in architectural engineering, along with three years hands-on experience.', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122381', 'Projects Management Engineering & Technical Feasibility Studies Services Abroad', 'Includes firms which work out primary technical and economic studies for constructions projects and for different commercial and economic establishments.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122382', 'Agricultural Pesticides Trading Abroad', 'Includes reselling materials intended for protection against and extermination and control of agricultural pests, including disease carriers affecting animals and plants. Pests are meant to be any plant or creature harmful or destructive, such as insects, spiders, nematodes, bacteria, fungal, moss, plant viruses, harmful weeds, parasitic plants, harmful birds, rodents, also, products plant growth controllers and crop protection.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122383', 'Basic Industrial Chemicals Trade (outside UAE)', 'Includes reselling intermediate chemicals such as resins, compounds, salts, sulfates, sulfurs, and others used in manufacturing by blending with other substances to produce paints, ink, cosmetics, detergents, fertilizers, pesticides, final chemical products, manufacturing metals, water purification and sterilization, in food industries such as preservatives, colorants, additives, flavors and fragrances, or in environment protection', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122384', 'Automobile Engineering Services Abroad', 'Includes providing services and consultancies related to vehicle engineering which incorporates the elements of design, mechanical, electrical, safety, fuel economy, noise, vibration, and harshness, performance', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122385', 'Waste Plastic Trading Abroad', 'Includes collecting and reselling all non- hazardous plastic waste, such as water bottles, boxes, shopping bags, dishes and food containers, after being used and disposed of by households, industrial and agricultural facilities, in order recycle and transform', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122386', 'Industrial & Liquefied Natural Gas Trading (Outside UAE)', 'Includes reselling of liquid gases used for industrial purposes, such as workshop welding, and gas for operating household air-conditioners and refrigerators, involving also, liquefied natural gas used for generation of electricity, production of hydrogen and ammonia after warming the LNG into natural gas.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122387', 'Aviation Consultancy Abroad', 'Includes firms specialized in providing aviation feasibility studies and consultancies as regarding airplanes buying and selling, fleet planning and aircraft selection, safety audits, crew selection and appointment, maintenance follow-up,aircraft registration, ownership transfer, lease delivery and return.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122388', 'Water, Sewage & Irrigation Engineering Services Abroad', 'Includes providing engineering consultancies and services outside UAE with regard to water, sewage and irrigation, including water purification plants and lines and reservoirs, sewer disposal plants and systems.', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122389', 'Aviation Business Brokerage Abroad', 'Includes firms engaged in variety of brokerage services regarding aviation business such as brokering flights on behalf of individuals and companies market for both passenger and cargo transportation, the sale and acquisition of aircrafts', 'Professional', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1122390', 'Tar & Asphalt Trading Abroad', 'Includes reselling tar and asphalt derived from petroleum distillation for using in road paving and water and humidity proofing in buildings.', 'Commercial', 'Outside Country', '', '', 'Non-Regulated', '', ''),
('IFZA', '1811006', 'Cards & Envelops Printing', 'Includes printing business cards, invitation cards to official events and celebrations, season''s greeting cards and weddings congratulations cards. This also includes printing the envelopes.', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '1812005', 'Design & Artwork Services', 'Includes providing a wide range of design and artworks to firms engaged in printing and publishing. This includes designing books, magazine covers, stamps, greeting cards and brochures, the process may take the traditional for modern techniques.', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '1820001', 'Audio Recorded Media Reproduction Studio', 'Includes firms engaged in reproducing sound recordings and radio programs in tapes and compact discs from the master copies of such records, such service is limited to small scale and is directly provided to the public.', 'Professional', '', '', 'Before license issuance', 'Regulated', 'Ministry of Culture & Youth', ''),
('IFZA', '3212002', 'Imitation Jewellery Smithing', 'Includes manufacturing goldsmiths'' articles, such as brooches, earnings, necklaces, bracelets, rings made from base metals plated with precious metals, or jewellery containing imitation stones such as imitation gems stones, imitation diamonds.', 'Professional', 'requires office/retail space', '', '', 'Non-Regulated', '', ''),
('IFZA', '3290024', '3D Printing Products Production', 'Includes firms specialized in producing products by the 3D printing through creating designs of objects with AutoCAD software, then the printer creates a three-dimensional object using lasers to fuse powdered materials together layer by layer, the powdered materials involve metal, plastic, rubber, silicon, ceramic, such technology involves different products and parts such as, jewelry, industrial parts, vehicles, dental and medical industry.', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '3315001', 'Ships & Boats Repair', 'Includes the reparation of vessels, wooden ships, yachts, sports boats, fishing ships and boats…etc. also, re-building, renovation, full maintenance, including refitting or replacement of motors and parts.', 'Professional', '', '', 'Before license issuance', 'Regulated', 'Dubai Maritime Authority', ''),
('IFZA', '3315009', 'Passengers & Cargo Aircrafts Repair & Maintenance', 'Includes firms engaged in maintaining, repairing, and modernizing passengers and cargo aircrafts to ensure their airworthiness, it involves aircrafts interior and system''s modifications, as well as internal and external aircrafts paint works.', 'Professional', '', '', 'Before license issuance', 'Regulated', 'Dubai Civil Aviation Authority', ''),
('IFZA', '3315101', 'Ships & Boats Maintenance Services', 'Includes firms that carry out ships and boats maintenanceas regarding re-painting and cleaning, as well as other simple operations which do not include reparations or total maintenance, which are classified under Class 3512.', 'Professional', '', '', 'Before license issuance', 'Regulated', 'Dubai Maritime Authority', ''),
('IFZA', '3319902', 'Heavy Duty Equipment & Machinery Repair & Maintenance', 'Includes firms repair machinery and equipment, lifts, escalators, boilers, central kitchens, automatic washing equipment, electric generators, water pumps, tower cranes…etc.', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '3319903', 'Marine Equipment Repairing & Maintenance', 'Includes installing and repairing the equipment related to structures for marine transportation, such as ships, boats, floating structures, pontoons, barges, cranes, the concerned equipment include propulsion systems, steering systems, engines, air-conditions, generators, ventilation blowers, boilers, spindles, pipes, communication and measuring devices.', 'Professional', '', '', 'Before license issuance', 'Regulated', 'Dubai Maritime Authority', ''),
('IFZA', '3320003', 'Wired & Wireless Communication Systems Installation', 'Includes firms specialized in the installation of equipment used in wired and wireless communications, including main switchboards such as switches and communication transmission and regulation devices, as well as equipment for communications ground stations, GPS systems by satellite and others.', 'Commercial', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '3811001', 'Garbage Disposal Services', 'Includes collecting of garbage and non-hazardous waste from residential, commercial, industrial and public areas, and then transport and dispose them in specified disposal sites determined by concerned authorities, it includes all municipal waste except construction and demolition waste, organic and horticultural waste.', 'Professional', '', '', 'After license issuance', 'Regulated', 'Waste Management', ''),
('IFZA', '3812007', 'Hazardous Waste Collection & Transport', 'Includes collecting solid and liquid or gaseous waste generated from manufacturing, medical or agricultural activities and which require special treatment as it cannot be disposed in regular landfills or sewer networks, because of it''s properties that make it dangerous or potentially harmful to human health or the environment. It involves the transportation by special vehicles to disposal sites determined by concerned authorities', 'Professional', '', '', 'Before license issuance', 'Regulated', 'Roads & Transport Authority', 'Dubai Municipality - Waste Department'),
('IFZA', '4290910', 'Sport Fields & Halls Contracting', 'Includes civil engineering works (except constructions) to install indoor and outdoor sport courts, fields, tracks and arenas. Works include flooring, walling, fencing, grandstand fixing and dismantling, as well as supply equipment made to international standards to enhance sport exercising and competitions.', 'Professional', 'Retail Space/Warehouse', '', 'After license issuance', 'Regulated', '', ''),
('IFZA', '4321004', 'Computer Network & Infrastructure Installation & Maintenance', 'Includes firms specialized in preparing and installing and maintaining the network and infrastructure of electronic computers, including the excavations for the extension cables and wires, optical fiber, and focal points as well as the attached devices such as servers and compounds connect (including wireless technology), so the composition of the electronic network a group of computers can benefit from the services provided by other computers linked to the network, it involves installing passive and active computer network and WIFI as well as the associated equipment and systems in large complexes such as hotels, hospitals, shopping malls …etc.', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '4321009', 'Security Equipment Installation & Maintenance', 'Includes installing security systems and equipment, such as security doors, metal detectors, thermal binoculars, and police specialized equipment, also, surveillance equipment such as observation cameras, anti-burglar, motion detectors, intercoms, alarms, access control, barrier gates, it involves repairing and maintaining such equipment.', 'Professional', '', 'Requires activity Security Systems & Equipment Trading existence on the same license', 'After license issuance', 'Regulated', 'Security Industry Regulatory Agency - SIRA', ''),
('IFZA', '4321011', 'Electricity Transmission & Control Equipment Installation Works', 'Includes firms engaged in installing and maintaining electric power transmission and distribution equipment and devices, such as current rectifiers, alternation controllers, operation panels, electric and electronic control apparatuses and distribution panels.', 'Commercial', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '4322008', 'Electromechanical Equipment Installation and Maintenance', 'Includes firms that install mechanical and electromechanical equipment, such as workshop equipment, factories, power generators, loading, lifting and towing equipment, cold rooms, refrigeration equipment, central kitchens, automatic laundry equipment, etc.', 'Professional', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '4330101', 'Fire & Smoke Resistant Doors, Windows, Walls & Partitions Installation', 'Includes installing smoke and fire-resistance rating doors, windows, walls and partitions made of glass, metal or timber in residential, commercial, healthcare or educational, and which are used as part of a passive fire protection system to reduce the spread of fire and smoke between separate compartments of a building and to enable safe escape of occupants in the event of a fire, as well as reducing the risk of the fire developing further.', 'Commercial', '', '', 'Before license issuance', 'Regulated', 'Dubai Civil Defense', ''),
('IFZA', '4390013', 'Fencing & Barbed Wire Installation Work', 'Includes installing and maintaining fence and barbed wire in industrial, agricultural installations, airports, military facilities to prevent crossing.', 'Professional', 'minimum space of 200 sqm', '', 'After license issuance', 'Regulated', '', ''),
('IFZA', '4510101', 'Motor Vehicles Trading', 'Includes reselling of new & used motor vehicles for personal use', 'Commercial', '', '', '', 'Non-Regulated', '', ''),
('IFZA', '4510102', 'Buses & Trucks Trading', 'Includes reselling different passenger buses, as well as trucks and trailers for transporting goods, liquid substances, building materials…etc.', 'Commercial', '', '', '', 'Non-Regulated', '', '');

-- Continue with more inserts (this is a sample of the first 50 activities)
-- Note: For production, you would want to insert all 850+ activities from the CSV

-- Add a trigger to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_business_activities_updated_at 
    BEFORE UPDATE ON business_activities 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
