default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # Use Supabase for development
  url: <%= ENV['DATABASE_URL'] %>
  prepared_statements: false

test:
  <<: *default
  # Use Supabase for testing (or local test database)
  url: <%= ENV['TEST_DATABASE_URL'] || ENV['DATABASE_URL'] %>

production:
  <<: *default
  # Use Supabase for production
  url: <%= ENV['DATABASE_URL'] %>
