default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simple_setup_development
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test:
  <<: *default
  database: simple_setup_test
  host: localhost
  port: 5432
  username: postgres
  password: postgres

production:
  <<: *default
  # Use Supabase URL in production
  url: <%= ENV['DATABASE_URL'] %>
